In [3]:
import numpy as np
import pandas as pd
import geopandas as gp
import os
import subprocess
import math
import shapely as shp
from datetime import datetime
from fiona.crs import from_epsg
import matplotlib.pylab as plt
import re
from pandas.tseries.holiday import get_calendar, HolidayCalendarFactory, GoodFriday
from datetime import datetime
from sklearn.model_selection import train_test_split


from itertools import compress

np.random.seed(222)

%matplotlib inline

/Users/geoffperrin/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [4]:
wd = os.getcwd()
os.chdir('../data')
os.getcwd()

'/Users/geoffperrin/Desktop/DLBA/demo_project/data'

In [5]:
#read in detroit feature dataset
city_df = pd.read_csv('CitywideIndicators_20170123.csv')

/Users/geoffperrin/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [24]:
#only keep DLBA Owned properties for the training data
dlba_df = city_df[city_df['Property Ownership'] == 'DLBA Owned']

#remove lots
dlba_df = dlba_df[dlba_df['Property Class'] != 'Residential-Lot']

dlba_df_small = dlba_df.rename(columns=lambda x: x.replace(' ', '_'))
dlba_df_small.head()

,Account_ID,Parcel_ID,Address,Property_Ownership,Property_Class,Program,Current_Status,Current_Status_Date,Neighborhood,Neighborhood_Sales_Median,...,MCM_Institutional_Use,MCM_Public_Use,MCM_Condition,MCM_Fire_Damage,MCM_Level_of_Fire_Damage,MCM_Boarding_Needed,MCM_Trespass,MCM_Vacant_Lot,MCM_Maintained,MCM_Dumping
3,001j000000h4Lo4,21021624.,16272 Lappin,DLBA Owned,Unknown-Lot,Inventory,Intake Review,1/29/2016,Regent Park,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,001j000000Idu4s,21007166.,13064 Elmdale,DLBA Owned,Residential-Structure,Own It Now,Sales Review,5/26/2016,Outer Drive-Hayes,1.40,...,NaN,NaN,Fair,No,NaN,No,NaN,NaN,NaN,Yes
62,001j000000Idu4y,21007448.001,14291 Elmdale,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,4/1/2016,Outer Drive-Hayes,1.40,...,NaN,NaN,Suggest Demolition,Yes,Major,Yes,Open,NaN,NaN,Yes
104,001j000000Idu5O,19005023.,4180 Cadillac,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,3/31/2016,Gratiot Woods,0.59,...,NaN,NaN,Poor,No,NaN,Yes,NaN,NaN,NaN,No
116,001j000000Idu5U,19005022.,4174 Cadillac,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,3/31/2016,Gratiot Woods,0.59,...,NaN,NaN,Fair,No,NaN,Yes,NaN,NaN,NaN,No

In [25]:
#read in detroit parcel distance to school df
school_df = pd.read_csv('DistanceToSchool_20170123.csv')
school_df_small = school_df[["PARCELNO", "DistanceToSchool_FT"]]
school_df_small.columns = ['Parcel_ID', 'dist_to_school']
school_df_small.head()

     Parcel_ID  dist_to_school
0    16006256.     2196.731029
1   04000103-4     2375.448135
2    04003341.     2442.534185
3  04003339-40     2510.715691
4    04000119.     2341.253487

In [26]:
#merge distance to school to city feature df
dlba_school_df = dlba_df_small.merge(school_df_small, on='Parcel_ID')
dlba_school_df.head()

,Account_ID,Parcel_ID,Address,Property_Ownership,Property_Class,Program,Current_Status,Current_Status_Date,Neighborhood,Neighborhood_Sales_Median,...,MCM_Public_Use,MCM_Condition,MCM_Fire_Damage,MCM_Level_of_Fire_Damage,MCM_Boarding_Needed,MCM_Trespass,MCM_Vacant_Lot,MCM_Maintained,MCM_Dumping,dist_to_school
0,001j000000Idu4s,21007166.,13064 Elmdale,DLBA Owned,Residential-Structure,Own It Now,Sales Review,5/26/2016,Outer Drive-Hayes,1.40,...,NaN,Fair,No,NaN,No,NaN,NaN,NaN,Yes,1235.838510
1,001j000000Idu4y,21007448.001,14291 Elmdale,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,4/1/2016,Outer Drive-Hayes,1.40,...,NaN,Suggest Demolition,Yes,Major,Yes,Open,NaN,NaN,Yes,2823.745964
2,001j000000Idu5O,19005023.,4180 Cadillac,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,3/31/2016,Gratiot Woods,0.59,...,NaN,Poor,No,NaN,Yes,NaN,NaN,NaN,No,758.959715
3,001j000000Idu5U,19005022.,4174 Cadillac,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,3/31/2016,Gratiot Woods,0.59,...,NaN,Fair,No,NaN,Yes,NaN,NaN,NaN,No,788.673532
4,001j000000Idu5y,18013649.,7729 American,DLBA Owned,Residential-Structure,Inventory,Intake Review,3/18/2015,Midwest,0.84,...,NaN,Poor,No,NaN,Yes,NaN,NaN,NaN,No,4959.561810

### Notes: current status is informative, but program is also informative

### perhaps add a feature that is the number of occupied properties within a buffer of every property - alice will send over parcel_ID lat/long data

In [27]:
len(dlba_school_df)

34014

In [31]:
#code up demo decision yes / no
demo_decision_dict = {'Demo Awaiting Funding': 1,
        'Demo Pipeline': 1,
        'Demo Contracted': 1,
        'Demo Review': 1,
        'Demolished': 999,
        'Construction Complete': 0,
        'Occupied': 0,
        'Sold': 0,
        'Institutional Partner Coordination': 999,
        'For Sale': 0,
        'Sales Review': 0,
        'Sales Pipeline': 0,
        'Vacant Land': 999,
        'Sales Hold': 0,
        'Under Construction': 999,
        'Lease/ROE/TLA': 999,
        'Warehouse': 999,
        'NPOC Isolation - Do not move!': 999,
        'NSP Quarantine': 999,
        'Reconveyance Complete': 999,
        'Title Problem Identified': 999,
        'DJ Quarantine': 999,
        'PDD Quarantine': 999,
        'Intake Review': 999}

dlba_school_df['demo_decision'] = 0
dlba_school_df['demo_decision'] = [demo_decision_dict[i] for i in dlba_school_df["Current_Status"]]
dlba_school_df = dlba_school_df[dlba_school_df['demo_decision'] != 999]

dlba_school_df.head()

,Account_ID,Parcel_ID,Address,Property_Ownership,Property_Class,Program,Current_Status,Current_Status_Date,Neighborhood,Neighborhood_Sales_Median,...,MCM_Maintained,MCM_Dumping,dist_to_school,demo_decision,fire_dummy,usps_vacant_dummy,foreclosed_dummy,foreclosure_lag,boarding_needed_dummy,dumping_dummy
0,001j000000Idu4s,21007166.,13064 Elmdale,DLBA Owned,Residential-Structure,Own It Now,Sales Review,5/26/2016,Outer Drive-Hayes,1.40,...,NaN,Yes,1235.838510,0,0,1,1,4.0,0,1
1,001j000000Idu4y,21007448.001,14291 Elmdale,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,4/1/2016,Outer Drive-Hayes,1.40,...,NaN,Yes,2823.745964,1,0,1,0,0.0,1,1
2,001j000000Idu5O,19005023.,4180 Cadillac,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,3/31/2016,Gratiot Woods,0.59,...,NaN,No,758.959715,1,0,1,1,6.0,1,0
3,001j000000Idu5U,19005022.,4174 Cadillac,DLBA Owned,Residential-Structure,HHF Demo,Demo Pipeline,3/31/2016,Gratiot Woods,0.59,...,NaN,No,788.673532,1,0,1,0,0.0,1,0
8,001j000000Idu66,18013642.,7777 American,DLBA Owned,Residential-Structure,Non-HHF Demo,Demo Awaiting Funding,3/28/2016,Midwest,0.84,...,NaN,No,5197.653491,1,0,1,1,4.0,1,0

In [32]:
len(dlba_school_df)

19579

In [36]:
#code NaNs as ... what?
dlba_school_df['fire_dummy'] = 0
dlba_school_df['fire_dummy'] = [0 if pd.isnull(i) else 1 for i in dlba_school_df['DFD_Fire:_Occurrence_Date']]

dlba_school_df['usps_vacant_dummy'] = 0
dlba_school_df['usps_vacant_dummy'] = [0 if pd.isnull(i) else 1 for i in dlba_school_df['USPS:_Vacancy_Indicated']]

dlba_school_df['foreclosed_dummy'] = 0
dlba_school_df['foreclosed_dummy'] = [0 if pd.isnull(i) else 1 for i in dlba_school_df['Foreclosure_Year']]

dlba_school_df['foreclosure_lag'] = 0
dlba_school_df['foreclosure_lag'] = [0 if pd.isnull(i) else (2017 - i) for i in dlba_school_df['Foreclosure_Year']]

dlba_school_df['boarding_needed_dummy'] = 0
dlba_school_df['boarding_needed_dummy'] = [0 if (pd.isnull(i) or i == 'No') else 1 for i in dlba_school_df['MCM_Boarding_Needed']]

dlba_school_df['dumping_dummy'] = 0
dlba_school_df['dumping_dummy'] = [0 if (pd.isnull(i) or i == 'No') else 1 for i in dlba_school_df['MCM_Dumping']]

dlba_school_df_small = dlba_school_df.drop(['Account_ID', 'Property_Ownership', 'Property_Class', 'Program', \
                                            'Current_Status', 'Current_Status_Date', 'Neighborhood', 'DNG_Number', \
                                            'WCT_Foreclosure_Status', \
                                            'MCM_Blext_Created_At', 'MCM_Structure', 'MCM_Occupancy',  'MCM_Use',\
                                           'MCM_Units', 'MCM_Residence_Type', 'MCM_Commercial_Use', 'MCM_Industrial_Use',\
                                           'MCM_Institutional_Use', 'MCM_Public_Use', 'MCM_Level_of_Fire_Damage', \
                                            'MCM_Trespass', 'MCM_Vacant_Lot', 'MCM_Maintained', 'DFD_Fire:_Occurrence_Date',\
                                           'USPS:_Vacancy_Indicated', 'Foreclosure_Year', 'MCM_Fire_Damage',\
                                           'USPS:_Last_Update', 'Occupancy_Model:_Last_Update', 'MCM_Boarding_Needed',\
                                           'MCM_Dumping'], 1)
dlba_school_df_small.head(5)

,Parcel_ID,Address,Neighborhood_Sales_Median,Occupancy_Model:_Probability_Pct,MCM_Condition,dist_to_school,demo_decision,fire_dummy,usps_vacant_dummy,foreclosed_dummy,foreclosure_lag,boarding_needed_dummy,dumping_dummy
0,21007166.,13064 Elmdale,1.40,14.54,Fair,1235.838510,0,0,1,1,4.0,0,1
1,21007448.001,14291 Elmdale,1.40,14.54,Suggest Demolition,2823.745964,1,0,1,0,0.0,1,1
2,19005023.,4180 Cadillac,0.59,14.54,Poor,758.959715,1,0,1,1,6.0,1,0
3,19005022.,4174 Cadillac,0.59,14.54,Fair,788.673532,1,0,1,0,0.0,1,0
8,18013642.,7777 American,0.84,14.54,Poor,5197.653491,1,0,1,1,4.0,1,0

In [ ]:
dlba_school_df_small = dlba_school_df_small.rename(columns={'Occupancy_Model:_Probability_Pct': 'occupancy_model_pct'})
dlba_school_df_small = dlba_school_df_small[['Parcel_ID', 'Address', 'demo_decision', 'Neighborhood_Sales_Median',\
                                            'occupancy_model_pct', 'MCM_Condition', 'dist_to_school',\
                                            'fire_dummy', 'usps_vacant_dummy', 'foreclosed_dummy',\
                                            'foreclosure_lag', 'boarding_needed_dummy', 'dumping_dummy']]

#fit model 
OS = []
IS = []

y = dlba_school_df_small.demo_decision
X = dlba_school_df_small.iloc[:,3:]
for i in range(10):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = i)
    
    lm =linear_model.LinearRegression()
    lm.fit(X_train, y_train)
    OS.append()